spring.application.name=pump-data-service

mqtt.broker=${MQTT_BROKER:tcp://localhost:1883}
mqtt.topic=${MQTT_TOPIC:plc/pump/data}
mqtt.clientId=${MQTT_CLIENT_ID:plc-springboot}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/pumpdb}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false